### ISSUE TITLE
Lisnr company use KissFFT library without attribution

### ISSUE THREAD

**Issue by nicolas-f** [mborgerding/kissfft#11]
The SDK of https://lisnr.com include the compiled functions of KissFFT (You can download Android Apk of Lisnr demo app and decompile it).

But I'm unable to find any attribution to KissFFT.

Do you have provided a commercial license to Lisnr ?

**Comment by mborgerding** [comment]
Thanks for the info.  Do you think it is possible you missed it?

LISNR responded to my inquiry with a copy of `NOTICE.txt` they reportedly include with their SDK.  It includes attribution to KISSFFT and others.

**Comment by nicolas-f** [comment]
Ok, nice, I missed it sorry. 

Its nice to see a big company use KissFFT.
