### ISSUE TITLE
Any chance of a recent labelled release?

### ISSUE THREAD

**Issue by fake-name** [mborgerding/kissfft#13]
The last proper release [was in 2012](https://github.com/mborgerding/kissfft/releases), and changes since then haven't been entered in the changelog.

I can just clone the current HEAD, but it'd be nice to have a proper release with a actual version number. Thanks!

------

Also, [we've](https://github.com/AkelaInc) been using KissFFT for in-house and some specialty applications, and it's been extremely easy to use and trouble free. Thanks for releasing it!

**Comment by generic-beat-detector** [comment]
Can I respectfully second this issue? [We](https://github.com/generic-beat-detector/GBD) also rely on KissFFT.

**Comment by mborgerding** [comment]
Not a whole lot has changed, but I suppose a new release is in order. l'd like to add github CI capabilities before then, but I don't have much time ... maybe this weekend.

**Comment by lucifetsmith** [comment]
I use kissfft and like it a lot. I'd like to provide some help to add github CI capabilities. How do you think about it?

**Comment by mborgerding** [comment]
Sounds good. There are some tests in there already that might be adapted.  Let me know what you need from me!

**Comment by lucifetsmith** [comment]
> Sounds good. There are some tests in there already that might be adapted. Let me know what you need from me!

Do you have any requirements/suggestions for the CI?  I prefer Travis, is that OK?

**Comment by lucifetsmith** [comment]
> No objection to Travis. If you are willing to help out and do the work, I'm not going to nitpick the choice of tools.
> 
> If you get Travis CI working on your fork of kissfft, then we can merge those changes into the baseline.
> I imagine that will lead to duplication of some of the the work -- setting up travis access (keys,tokens,etc) twice, but I'd like to see it working first on a fork.

The Travis CI has been constructed on my fork. [https://github.com/lucifetsmith/kissfft](url)
 - create .travis.yml to perform CI
 - create README.md based on README, little modification to adapt to Markdown syntex

Any suggestion to make it better?

**Comment by lucifetsmith** [comment]
I guess a new release is wanted by a lot of people. Do you have any plan for it? If anything I can help, let me know.

**Comment by mborgerding** [comment]
v131 now released.  Thanks @lucifetsmith for the Travis help

**Comment by fake-name** [comment]
Wewt!
