### ISSUE TITLE
Test code running issue

### ISSUE THREAD

**Issue by sunzhuoshi** [mborgerding/kissfft#25]
I'm trying to learn the code and I found there are some python test code, but I failed to run "compfft.py" with "ModuleNotFoundError: No module named 'FFT'", and I noticed that there are both "FFT" and "fft" module import in this source file. Thanks for any help.
#

**Comment by mborgerding** [comment]
Sorry for leaving that broken code laying around.  I cringed twice when I saw `from Numeric import *`.
Please don't look at that code anymore, it may hurt your eyes and brain.

**Comment by sunzhuoshi** [comment]
well, thank you for your reply all the same.
