### ISSUE TITLE
Is it possible to change fft data type during run time?

### ISSUE THREAD

**Issue by chensterliu** [mborgerding/kissfft#34]
Hello,

my project requires multiple FFTs with different data types (int32, int16). It seems that the kiss_fft_scalar is fixed after compiling. I tried to define FIXED_POINT with different values in the code, but the result is incorrect. Could anyone tell me if my requirement is possible to be met?

Best

**Comment by mborgerding** [comment]
You'd have to make the changes yourself.  I must ask one question -- are you sure you want fixed point FFTs?  If so, is there a vendor supplied FFT library you should be using?

**Comment by chensterliu** [comment]
We are working on FFT hardware implementation, just use this software code for reference. So no such vendor.

**Comment by mborgerding** [comment]
Sorry, that is not really supported at the current time.
But you might be able to do one of the following.

*  compile kissfft into different shared libs, having an interface that is unique to the data type.
*  perform the computation in separate executable utilities
*  use the preprocessor to effectively make K copies of the library for the K different data types.e.g.  
```
#define kiss_fft_alloc kiss_fft_alloc_int32
#define kiss_fft kiss_fft_int32
... and so on, then
#include "kiss_fft.c"
```

**Comment by chensterliu** [comment]
That's an awesome solution, thanks for your hints.
