### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by sunbubble** [mborgerding/kissfft#35]
https://github.com/mborgerding/kissfft/blob/1efe72041e00868c3c71eaf569343ee132a4fbb9/kissfft.hh#L129

Shouldn't this be (note the zero) ?
```
        /// stored in @c dst[0].real() and @c dst[0].imag() respectively.
```

**Comment by seeker-Liu** [comment]
+1. It should be, and there could be a easy fix for this, isn't it?

**Comment by seeker-Liu** [comment]
https://github.com/mborgerding/kissfft/pull/50
This pull request should fix this, idk why I can't link this issue and the pull request automatically.

**Comment by madebr** [comment]
I think this issue can be closed.
