### ISSUE TITLE
kiss_fftr(cfg, kiss_fft_scalar* timedata, kiss_fft_cpx* freqdata) overflows freqdata?

### ISSUE THREAD

**Issue by Fillipoman** [mborgerding/kissfft#44]
The header file has the following:
void kiss_fftr(kiss_fftr_cfg cfg,const kiss_fft_scalar *timedata,kiss_fft_cpx *freqdata);
/*
 input timedata has nfft scalar points
 output freqdata has nfft/2+1 complex points
*/

However, it seems that kiss_fftr fills freqdata with data up to nfft complex points, causing an overflow when using a freqdata buffer with only nfft/2 + 1 complex points allocated. Is this the expected behavior? Am I missing something in the documentation?

I can post some example code if that helps.

**Comment by mborgerding** [comment]
Examples would be good

**Comment by Fillipoman** [comment]
`void ComputeAudioInFfts(AppState* app_state) {
    ASSERT(sizeof(kiss_fft_scalar) == sizeof(float));
    ASSERT(sizeof(kiss_fft_cpx) == 2 * sizeof(float));

    // NOTE: for KissFFT these need to be powers of 2
    AggregateAudioInput* aggregate_audio = &app_state->aggregate_audio_input;
    uint32 desired_fft_input_samples = (uint32)(app_state->active_scene->audio_lookback * aggregate_audio->sample_rate);
    uint32 fft_input_samples = RoundUpToPowerOf2(desired_fft_input_samples);
    // NOTE: For the real FFT, the number of outputted frequency bins is half the input
    uint32 fft_num_freq_bins = fft_input_samples / 2;

    // Assign the maximum size available. kiss_fftr_alloc will re-assign with
    // the used size if sufficient.
    size_t fft_cfg_input_size = UnusedSize(*frame_transient_arena);
    kiss_fftr_cfg fft_cfg_input =
        kiss_fftr_alloc(fft_input_samples, 0, BasePlusUsed(*frame_transient_arena), &fft_cfg_input_size);
    ASSERT(fft_cfg_input_size <= UnusedSize(*frame_transient_arena));
    PushSize_(frame_transient_arena, fft_cfg_input_size);

    // NOTE: Add one to the fft_num_freq_bins as the output also includes the DC at 0th entry
    kiss_fft_cpx* left_input_freqdata = PushArrayAndZero(frame_transient_arena, fft_num_freq_bins + 1, kiss_fft_cpx);
    kiss_fft_cpx* right_input_freqdata = PushArrayAndZero(frame_transient_arena, fft_num_freq_bins + 1, kiss_fft_cpx);
    kiss_fft_cpx* mono_input_freqdata = PushArrayAndZero(frame_transient_arena, fft_num_freq_bins + 1, kiss_fft_cpx);

    kiss_fft_scalar* left_input_timedata = PushArrayAndZero(frame_transient_arena, fft_input_samples, kiss_fft_scalar);
    kiss_fft_scalar* right_input_timedata = PushArrayAndZero(frame_transient_arena, fft_input_samples, kiss_fft_scalar);
    kiss_fft_scalar* mono_input_timedata = PushArrayAndZero(frame_transient_arena, fft_input_samples, kiss_fft_scalar);
`
then there is some code to copy the audio signal data into the timedata buffers and finally I call

` kiss_fftr(fft_cfg_input, right_input_timedata, right_input_freqdata);
    kiss_fftr(fft_cfg_input, left_input_timedata, left_input_freqdata);
    kiss_fftr(fft_cfg_input, mono_input_timedata, mono_input_freqdata);
`
and I can see that some frequency data gets overflowed into left_input_timedata which makes sense as it is the next portion in the memory arena after the freqdata buffers. I can see the overfill go away when I allocate my freqdata buffers with fft_input_samples as the count parameter.

**Comment by Fillipoman** [comment]
Hold on, I'm going to looks more closely at my memory allocation code....

**Comment by Fillipoman** [comment]
Alright, my apologies. I checked the size of my buffers more closely now and realized there was a very egregious error with my PushArrayAndZero macro.
I had #define PushArrayAndZero(arena, count, type) (type*)PushSizeAndZero_(arena, count * sizeof(type))
which was resolving to
PushSizeAndZero_(arena, fft_num_freq_bins + 1 * sizeof(type)) !!!!!!!!
The fixed macro is now #define PushArrayAndZero(arena, count, type) (type*)PushSizeAndZero_(arena, (count) * sizeof(type))
Very sorry to waste your time with this post. Should have double checked more closely before posting.

**Comment by Fillipoman** [comment]
And thanks for the wonderful library! I've really been enjoying the well designed API

**Comment by mborgerding** [comment]
Glad you resolved it. You're welcome.
