### ISSUE TITLE
iFFT waveform type

### ISSUE THREAD

**Issue by siditious** [mborgerding/kissfft#48]
I noticed that by default the program rebuilds real signal using square waves, is there an easy way to change this to use sine waves instead? It doesn't affect simple fft operations too much but the square waves do create some issues when doing any form of manipulative analysis.

**Comment by mborgerding** [comment]
Did you intend to write this issue against kissfft? It doesn't make much sense to me

**Comment by siditious** [comment]
No I wasn't writing an issue against it sorry, the implementation works fine as is I was just curious if there was a way to do it.

**Comment by mborgerding** [comment]
I suggest dsp.stackexchange.com for such questions

**Comment by siditious** [comment]
Well it is a library specific question, and considering not many people use this compared to FFTW I haven't found a lot of useful information.

**Comment by mborgerding** [comment]
As I said, I don't understand your question. Give specifics

**Comment by siditious** [comment]
So I noticed that the ifft being returned from the library has square waveforms, which is probably a result of the classic DFT implementation with orthogonal sinusoids, I was just curious if you knew of any way to effectively implement additive synthesis using standard sine waves into this particular algorithm, or if it was already implemented.  Sorry I know it's a really specific and probably strange request but I figured it couldn't hurt to ask.
