### ISSUE TITLE
Make a radix 2 twiddle table once one and reuse?

### ISSUE THREAD

**Issue by Alex-EEE** [mborgerding/kissfft#59]
Is there a way to create the twiddle table just once at program start, and reuse it for different fft sizes ( only for power of 2 fft sizes)?  Other libraries typically do this, you just have to create a twiddle table once for the max size, then you use a stride to reuse the twiddle table for different size ffts

**Comment by mborgerding** [comment]
It might not be too hard for you to change your version, but no ... what you suggest is not possible through the current interface.
