### ISSUE TITLE
Could you tell me the theory of the detail implement about kissfft ?

### ISSUE THREAD

**Issue by wenwu-glagle** [mborgerding/kissfft#63]
Could you tell me the theory of the detail implement about kissfft, maybe a book or web.

I am confused about the code like in kiss_fftr(): 
```
    for ( k=1;k <= ncfft/2 ; ++k ) {
        fpk    = st->tmpbuf[k]; 
        fpnk.r =   st->tmpbuf[ncfft-k].r;
        fpnk.i = - st->tmpbuf[ncfft-k].i;
        C_FIXDIV(fpk,2);
        C_FIXDIV(fpnk,2);

        C_ADD( f1k, fpk , fpnk );
        C_SUB( f2k, fpk , fpnk );
        C_MUL( tw , f2k , st->super_twiddles[k-1]);

        freqdata[k].r = HALF_OF(f1k.r + tw.r);
        freqdata[k].i = HALF_OF(f1k.i + tw.i);
        freqdata[ncfft-k].r = HALF_OF(f1k.r - tw.r);
        freqdata[ncfft-k].i = HALF_OF(tw.i - f1k.i);
    }
```

Thanks.

**Comment by abfan1127** [comment]
Its probably best to start with the Wikipedia Entry for Fast Fourier Transform, then build up from there.  Know that the FFTR assumes the input is a Real valued input (as opposed to complex value). 

[https://en.wikipedia.org/wiki/Fast_Fourier_transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform)

**Comment by mborgerding** [comment]
[This](http://dsp-book.narod.ru/FFTBB/0270_PDF_C14.pdf) might help explain the `kiss_fftr` code.  Two FFTs are done in parallel of the even and odd sequences, then recombined.
