### ISSUE TITLE
Question on fixed point scaling

### ISSUE THREAD

**Issue by robiwano** [mborgerding/kissfft#72]
Acc. to the docs, fixed point FFT performs scaling (both ways) because of overflow issues. Is it possible to inhibit the scaling so it works the same as for floating point?

**Comment by robiwano** [comment]
Ok, I see that it is the C_FIXDIV that do this.

**Comment by stolk** [comment]
I have the same issue when using `int16_t` . I kinda expected to have fftr followed by fftri result in roughly the save data?

```
        setup_reference_wave();

        // Create configurations.
        kiss_fftr_cfg cfg  = kiss_fftr_alloc(SZ,0,0,0); // Time to Freq.
        kiss_fftr_cfg cfgi = kiss_fftr_alloc(SZ,1,0,0); // Inverse: Freq to Time.

        // Use configurations.
        kiss_fftr(cfg, reference_wave, outp);

        kiss_fftri(cfgi, outp, reconstructed_wave);

        // Clean up configuration.
        free(cfgi);
        free(cfg);

        for (int i=0; i<SZ; ++i)
                fprintf(stdout,"%d -> %d\n", reference_wave[i], reconstructed_wave[i]);
```

My original wave was scaled from -7fff to 7fff, and my reconstructed wave is from -64 to 63? Is that as expected?

**Comment by robiwano** [comment]
It comes down to the implementation. I understand why KISSFFT does the scaling, so unfortunately yes, in the case of KISSFFT it is to be expected. You have to scale up the result from the FFT before passing it to the iFFT.
