### ISSUE TITLE
Inverse FFT Broken

### ISSUE THREAD

**Issue by littlemanrkc** [mborgerding/kissfft#9]
The following code does not produce the expected answer:
// -------------------
	kiss_fft_cpx data[3];
	data[0].r = 1;
	data[0].i = 2;
	data[1].r = 3;
	data[1].i = 4;
	data[2].r = 5;
	data[2].i = 6;

	kiss_fft_cfg fft = kiss_fft_alloc (3, 0, nullptr, nullptr);
	kiss_fft_cfg ifft = kiss_fft_alloc (3, 1, nullptr, nullptr);

	kiss_fft (fft, data, data);  // correct result
	kiss_fft (ifft, data, data); // incorrect result
// -------------------
The intermediate result for the forward FFT matches the output Matlab gives, but the inverse FFT on that forward FFT data does not get back to the original data. This is using the code downloaded from GIT without any modifications.

**Comment by mborgerding** [comment]
read README
